/*
Copyright 2022 The efucloud.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/efucloud/api/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkspaceGroups implements WorkspaceGroupInterface
type FakeWorkspaceGroups struct {
	Fake *FakeRbacV1alpha1
}

var workspacegroupsResource = schema.GroupVersionResource{Group: "rbac.efucloud.com", Version: "v1alpha1", Resource: "workspacegroups"}

var workspacegroupsKind = schema.GroupVersionKind{Group: "rbac.efucloud.com", Version: "v1alpha1", Kind: "WorkspaceGroup"}

// Get takes name of the workspaceGroup, and returns the corresponding workspaceGroup object, and an error if there is any.
func (c *FakeWorkspaceGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkspaceGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(workspacegroupsResource, name), &v1alpha1.WorkspaceGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceGroup), err
}

// List takes label and field selectors, and returns the list of WorkspaceGroups that match those selectors.
func (c *FakeWorkspaceGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkspaceGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(workspacegroupsResource, workspacegroupsKind, opts), &v1alpha1.WorkspaceGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkspaceGroupList{ListMeta: obj.(*v1alpha1.WorkspaceGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkspaceGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workspaceGroups.
func (c *FakeWorkspaceGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(workspacegroupsResource, opts))
}

// Create takes the representation of a workspaceGroup and creates it.  Returns the server's representation of the workspaceGroup, and an error, if there is any.
func (c *FakeWorkspaceGroups) Create(ctx context.Context, workspaceGroup *v1alpha1.WorkspaceGroup, opts v1.CreateOptions) (result *v1alpha1.WorkspaceGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(workspacegroupsResource, workspaceGroup), &v1alpha1.WorkspaceGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceGroup), err
}

// Update takes the representation of a workspaceGroup and updates it. Returns the server's representation of the workspaceGroup, and an error, if there is any.
func (c *FakeWorkspaceGroups) Update(ctx context.Context, workspaceGroup *v1alpha1.WorkspaceGroup, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(workspacegroupsResource, workspaceGroup), &v1alpha1.WorkspaceGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkspaceGroups) UpdateStatus(ctx context.Context, workspaceGroup *v1alpha1.WorkspaceGroup, opts v1.UpdateOptions) (*v1alpha1.WorkspaceGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(workspacegroupsResource, "status", workspaceGroup), &v1alpha1.WorkspaceGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceGroup), err
}

// Delete takes name of the workspaceGroup and deletes it. Returns an error if one occurs.
func (c *FakeWorkspaceGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(workspacegroupsResource, name, opts), &v1alpha1.WorkspaceGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkspaceGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(workspacegroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkspaceGroupList{})
	return err
}

// Patch applies the patch and returns the patched workspaceGroup.
func (c *FakeWorkspaceGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(workspacegroupsResource, name, pt, data, subresources...), &v1alpha1.WorkspaceGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkspaceGroup), err
}
